name: weatherapi
description: A plugin for fetching weather forecasting via WeatherAPI.com. Works for both Android and iOS.
version: 1.1.0
homepage: https://github.com/lorenzocopelli/weatherapi

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
