enum Language {
  arabic,
  bengali,
  bulgarian,
  chineseSimplified,
  chineseTraditional,
  czech,
  danish,
  dutch,
  english,
  finnish,
  french,
  german,
  greek,
  hindi,
  hungarian,
  italian,
  japanese,
  javanese,
  korean,
  mandarin,
  marathi,
  polish,
  portuguese,
  punjabi,
  romanian,
  russian,
  serbian,
  sinhalese,
  slovak,
  spanish,
  swedish,
  tamil,
  telugu,
  turkish,
  ukrainian,
  urdu,
  vietnamese,
  wuShanghainese,
  xiang,
  yueCantonese,
  zulu
}

Map<Language, String> languageCodes = {
  Language.arabic: 'ar',
  Language.bengali: 'bn',
  Language.bulgarian: 'bg',
  Language.chineseSimplified: 'zh',
  Language.chineseTraditional: 'zh_tw',
  Language.czech: 'cs',
  Language.danish: 'da',
  Language.dutch: 'nl',
  Language.finnish: 'fi',
  Language.french: 'fr',
  Language.german: 'de',
  Language.greek: 'el',
  Language.hindi: 'hi',
  Language.hungarian: 'hu',
  Language.italian: 'it',
  Language.japanese: 'ja',
  Language.javanese: 'jv',
  Language.korean: 'ko',
  Language.mandarin: 'zh_cmn',
  Language.marathi: 'mr',
  Language.polish: 'pl',
  Language.portuguese: 'pt',
  Language.punjabi: 'pa',
  Language.romanian: 'ro',
  Language.russian: 'ru',
  Language.serbian: 'sr',
  Language.sinhalese: 'si',
  Language.slovak: 'sk',
  Language.spanish: 'es',
  Language.swedish: 'sv',
  Language.tamil: 'ta',
  Language.telugu: 'te',
  Language.turkish: 'tr',
  Language.ukrainian: 'uk',
  Language.urdu: 'ur',
  Language.vietnamese: 'vi',
  Language.wuShanghainese: 'zh_wuu',
  Language.xiang: 'zh_hsn',
  Language.yueCantonese: 'zh_yue',
  Language.zulu: 'zu'
};
